### ISSUE TITLE
Build failure due to GHC option "-threaded"

### ISSUE THREAD

**Issue by ralphtq** [robstewart57/rdf4h#88]
I am building rdf4h with "allow-newer: true" (because of other dependency issues with ghc 8.10.1 working with cabal 3.0.0)  and get the following errors (using stack):

```
rdf4h     > 20 | import Data.Semigroup ((<>))
rdf4h     >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rdf4h     > [14 of 17] Compiling Text.RDF.RDF4H.XmlParser.Xmlbf
rdf4h     >
rdf4h     > /private/var/folders/yk/nlh57w1n5vl7stv4vsxqfz4w0000gn/T/stack-ff9cd829529d5b68/rdf4h-4.0.0/src/Text/RDF/RDF4H/XmlParser/Xmlbf.hs:432:3: error:
rdf4h     >     ‘fail’ is not a (visible) method of class ‘Monad’
rdf4h     >     |
rdf4h     > 432 |   fail = pFail
rdf4h     >     |   ^^^^
rdf4h     >
rdf4h     > /private/var/folders/yk/nlh57w1n5vl7stv4vsxqfz4w0000gn/T/stack-ff9cd829529d5b68/rdf4h-4.0.0/src/Text/RDF/RDF4H/XmlParser/Xmlbf.hs:433:14: error:
rdf4h     >     The INLINE pragma for ‘fail’ lacks an accompanying binding
rdf4h     >       (The INLINE pragma must be given where ‘fail’ is declared)
rdf4h     >     |
rdf4h     > 433 |   {-# INLINE fail #-}
rdf4h     >     |              ^^^^
rdf4h     >

Error:
--  While building package rdf4h-4.0.0 using:
      /Users/ralphtq/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

Warning: Build failed, but trying to launch GHCi anyway
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: edg-snomed
Progress 1/2GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package rdf4h-4.0.0
    (use -v for more information)
```

By copying source files into my own stack I was able to get a successful build by setting these dependencies (the ones after the single dependency commented out for rdf4h): 

```
 build-depends:
      aeson
    , base >= 4.8
    , bytestring
    , cassava >= 0.4
    , text >= 1.2 && < 1.3
    , vector >= 0.11
    , unordered-containers >= 0.2.10.0
    , hashable >= 1.3.0.0
    , containers >= 0.6.2.1
    , regex-compat >= 0.95.2.0
    , regex-posix >= 0.96.0.0
    -- , rdf4h >= 4.0.0
    , binary >= 0.8.7.0
    , network-uri >= 2.6.3.0
    , filepath >= 1.4.2.1
    , deepseq >= 1.4.4.0
    , parsec >= 3.1.14.0
    , parsers >= 0.12.10
    , attoparsec >= 0.13.2.4
    , hgal >= 2.0.0.2
    , algebraic-graphs >= 0.4
    , lifted-base  >= 0.2.3.12
    , http-conduit >= 2.3.7.3
    , mtl >= 2.2.2
    , exceptions >= 0.10.4
    , mmorph >= 1.1.3
    , selective >= 0.3
    , html-entities >= 1.1.4.3
    , xeno >= 0.3.5.2
```

I also had to make this change to my local copy of "AlgebraicGraph.hs":

```
data instance RDF AlgebraicGraph
  = AlgebraicGraph
      { _graph :: G.Graph (HashSet Node) Node,
        _baseUrl :: Maybe BaseUrl,
        _prefixMappings :: PrefixMappings
      }
    deriving (Generic)    -- RH20200517
  -- deriving (Generic, NFData)
```

I was then able to run:

```
testRDF :: IO ()
testRDF = do
  -- empty list based RDF graph
  let myEmptyGraph = empty :: RDF TList

  -- add a triple to the empty graph
      triple1 = triple
        (unode "http://www.example.com/rob")
        (unode "http://xmlns.com/foaf/0.1/interest")
        (unode "http://dbpedia.org/resource/Scotch_whisky")
      graph1 = addTriple myEmptyGraph triple1

  -- add another triple to the graph
      triple2 = triple
        (unode "http://www.example.com/rob")
        (unode "http://xmlns.com/foaf/0.1/interest")
        (unode "http://dbpedia.org/resource/Haskell_(programming_language)")
      graph2 = addTriple graph1 triple2

  -- remove one of my interests
      graph3 = removeTriple graph2 triple1

  putStrLn (showGraph graph3)
```

Perhaps the build issue has to do with running with the latest ghc version?

**Comment by robstewart57** [comment]
Hi @ralphtq , thanks for this report.

I've just uploaded version 4.0.1 of rdf4

http://hackage.haskell.org/package/rdf4h-4.0.1

Which I expect will resolve your issue. Version 4.0.1 compiles with GHC versions from 8.0.2 to 8.8.3.

Please let me know if your issue isn't resolved by rdf4h-4.0.1, thanks.
